---
name: Portfolio Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Github page
        uses: actions/configure-pages@v4
      - name: Deploy to Github Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: .
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
